good_heartst_project/animals/urls.py
from django.urls import path, include
from .views import AnimalList, AnimalPostDetail, CategoryList, CreatView

app_name = 'animals'

urlpatterns = [
    path('', AnimalList.as_view(), name='list'),
    path('category/<int:category_id>/', CategoryList.as_view(), name='category'),
    path('<slug:animals_slug>/', AnimalPostDetail.as_view(), name='detail'),
    path('add_post', CreatView.as_view(), name='add'),

]

good_heartst_project/good_heartst_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('animals.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

good_heartst_project/users/urls.py
from django.urls import path, include

from . import views as vw

app_name = 'users'

urlpatterns = [
    path('signup/', vw.SignUp.as_view
         (template_name='users/signup.html'),
         name='signup'
         ),
]

good_heartst_project/templates/include/_navbar.html
<nav class="navbar bg-light fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'animals:list'%}">Доброе сердце </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Доброе сердце Элиста</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          {% for i in animal %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'animals:category' i.category.id %}">{{i.category}}</a>
          </li>
         {% endfor %}
         <li class="nav-item">
            <a class="nav-link" href="{% url 'animals:add' %}">Добавить пост </a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="offcanvasNavbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu" aria-labelledby="offcanvasNavbarDropdown">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </div>
</nav>

good_heartst_project/templates/include/base.html
{% load static %}
<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="./style.css">
    <link rel="stylesheet" type="text/css" href="{% static 'animals.css' %}">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" rel="stylesheet"/> 
  </head>
  <body>
  
    {% block content%}
    {% include 'include/_navbar.html'%}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>

good_heartst_project/templates/include/card.html
<div class="container">
    <div class="post">
        <div class="post-image">
            <img src="https://html5book.ru/wp-content/uploads/2019/03/postimage6.jpg">
        </div>
        <div class="post-content">
            <div class="post-header">
                <h1>Как бы то ни было, консультация с широким активом оказалась чрезвычайно полезной</h1>
                <div class="post-meta">
                    <time datetime="2019-04-01">Апрель, 1</time>
                    <span class="author">Ирина Клубничная</span>
                    <span class="category">Философия</span>
                </div>
            </div>
            <p>С другой стороны, разбавленное изрядной долей эмпатии, рациональное мышление обеспечивает
                актуальность системы массового участия. В своем стремлении улучшить пользовательский опыт мы
                упускаем, что интерактивные прототипы, вне зависимости от их уровня, должны быть ассоциативно
                распределены по отраслям.
            </p>
        </div>
    </div>
</div>

good_heartst_project/templates/include/footer.html
 <div class="footer-basic">
        <footer>
            <div class="social"><a href="#"><i class="icon ion-social-instagram"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-facebook"></i></a></div>
            <ul class="list-inline">
                <li class="list-inline-item"><a href="#">Home</a></li>
                <li class="list-inline-item"><a href="#">Services</a></li>
                <li class="list-inline-item"><a href="#">About</a></li>
                <li class="list-inline-item"><a href="#">Terms</a></li>
                <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
            </ul>
            <p class="copyright">Company Name © 2018</p>
        </footer>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>